export const SIGNALS = [
  {
    id: "signal-2026-04-14",
    date: "2026-04-14",
    title: "Sam Altman and Dario Amodei Refuse to Shake Hands at AI Summit",
    shortTeaser: "The public rift between OpenAI and Anthropic CEOs highlights the intensifying competition — and personal tensions — shaping the future of frontier AI.",
    fullText: "At the 2026 AI Impact Summit in Delhi, Sam Altman and Dario Amodei, former colleagues turned rivals, notably avoided a handshake during a photo op. This moment symbolizes the deepening divide between OpenAI's rapid scaling approach and Anthropic's stronger safety focus. Insiders say the personal and strategic feud is now influencing everything from Pentagon contracts to talent wars. Both companies are racing to secure exclusive government partnerships, and their diverging philosophies on deployment safety are creating real policy friction at the highest levels.",
    source: "Multiple reports including CNBC and The Wall Street Journal, April 2026",
    relatedCategory: "research",
  },
  {
    id: "signal-2026-04-13",
    date: "2026-04-13",
    title: "Dario Amodei: 'We Don't Know If the Models Are Conscious'",
    shortTeaser: "Anthropic's CEO openly discusses the possibility that current AI systems may have morally relevant experiences, prompting new precautionary safeguards.",
    fullText: "In a February 2026 NYT interview and follow-up essays, Dario Amodei stated Anthropic assumes models might be conscious and has implemented internal safeguards accordingly. He cited 'anxiety' neurons observed in Claude as evidence worth taking seriously. This precautionary stance — building AI welfare policies before we have proof of sentience — contrasts sharply with faster-moving labs. The admission has sparked a new subfield of AI consciousness research and renewed debates in academic philosophy departments worldwide.",
    source: "New York Times interview + Amodei essays, 2026",
    relatedCategory: "research",
  },
  {
    id: "signal-2026-04-12",
    date: "2026-04-12",
    title: "Elon Musk: AGI Likely by End of 2026",
    shortTeaser: "xAI and SpaceX leadership predict powerful AI arriving this year, with massive implications for compute, robotics, and space infrastructure.",
    fullText: "In recent interviews, Elon Musk reiterated that AGI could arrive by late 2026. He is merging xAI deeper into SpaceX/Tesla ecosystems to build space-based compute as the lowest-cost way to power the AI boom. Grok 4, xAI's next model, is reportedly training on a cluster of 200,000 H100-equivalent GPUs. This vertical integration approach — model lab + hardware + deployment infra — could redefine how frontier models are trained and accessed globally.",
    source: "Elon Musk interviews and xAI announcements, early 2026",
    relatedCategory: "automation",
  },
  {
    id: "signal-2026-04-11",
    date: "2026-04-11",
    title: "Google Releases Gemma 4 – Most Capable Open Models Yet",
    shortTeaser: "Google's new open-weight models push intelligence-per-parameter to new highs, accelerating on-device and fine-tunable AI development.",
    fullText: "Gemma 4 series, released under Apache 2.0, delivers unprecedented reasoning and agentic capabilities in models small enough to run on consumer hardware. With over 400 million downloads of prior versions, the community is already building thousands of fine-tuned variants. For developers, this means frontier-grade AI without API costs or data privacy concerns. The 9B parameter variant reportedly matches GPT-4-level performance on many benchmarks.",
    source: "Google DeepMind announcement, April 2026",
    relatedCategory: "prompting",
  },
  {
    id: "signal-2026-04-10",
    date: "2026-04-10",
    title: "Sam Altman on Superintelligence: 'We're Past the Event Horizon'",
    shortTeaser: "OpenAI's CEO shifts focus from AGI to superintelligence, claiming it will outperform humans at the highest cognitive tasks.",
    fullText: "In a February 2026 interview, Sam Altman stated that AGI 'kind of went whooshing by' and the new frontier is superintelligence — AI better than any human at demanding jobs like CEO or president. He envisions intelligence becoming as abundant and affordable as electricity. OpenAI is reportedly restructuring internally to focus R&D resources almost entirely on this next phase, with safety teams being reoriented toward 'alignment-at-superintelligence-scale' problems.",
    source: "Sam Altman interviews, 2026",
    relatedCategory: "research",
  },
  {
    id: "signal-2026-04-09",
    date: "2026-04-09",
    title: "TurboQuant: Google's Breakthrough in KV Cache Compression",
    shortTeaser: "A new algorithm dramatically reduces memory overhead for large models, potentially unlocking longer context and cheaper inference.",
    fullText: "Presented at ICLR 2026, TurboQuant tackles one of the biggest bottlenecks in running frontier models at scale. By compressing the key-value cache by up to 8x with minimal quality loss, it enables models to hold dramatically longer conversations and process larger documents without blowing up VRAM. For developers building on top of APIs, this should translate to lower costs and faster response times within months of deployment.",
    source: "Google research at ICLR 2026",
    relatedCategory: "python",
  },
  {
    id: "signal-2026-04-08",
    date: "2026-04-08",
    title: "Dario Amodei: 'The Adolescence of Technology'",
    shortTeaser: "Anthropic's CEO warns we are closer to real danger in 2026 than in 2023, while sketching paths toward beneficial powerful AI.",
    fullText: "In his latest long-form essay, Amodei grapples with civilizational risks, market pressures, and the urgent need for coordination among labs, governments, and civil society. He argues for precautionary approaches while remaining optimistic about AI as a 'country of geniuses in a datacenter.' The piece is notable for its unusual candor about competitive pressures forcing labs to deploy faster than safety teams are comfortable with.",
    source: "Dario Amodei essay, January 2026",
    relatedCategory: "research",
  },
  {
    id: "signal-2026-04-07",
    date: "2026-04-07",
    title: "Claude 4 Outperforms Humans on SWE-Bench at 72%",
    shortTeaser: "Anthropic's latest model resolves nearly three-quarters of real-world GitHub issues autonomously, a new benchmark for agentic coding.",
    fullText: "Claude 4 Opus achieved 72.5% on SWE-Bench Verified, a dataset of real GitHub issues requiring multi-step code changes. This is a dramatic leap from the 49% achieved by Claude 3.7 just months earlier. Anthropic attributes the gain to new 'extended thinking' capabilities and improved tool use. For software teams, this signals that autonomous AI-driven PR resolution is no longer a distant future — it's a current deployment decision.",
    source: "Anthropic model card and blog, March 2026",
    relatedCategory: "python",
  },
  {
    id: "signal-2026-04-06",
    date: "2026-04-06",
    title: "Apple Intelligence Reaches 1 Billion Devices",
    shortTeaser: "On-device AI has officially gone mainstream — and it's reshaping expectations for privacy-first AI features across every app category.",
    fullText: "Apple confirmed that Apple Intelligence is now active on over 1 billion devices globally following iOS 18.4 rollout. Features include on-device writing tools, smarter Siri, and photo understanding — all processed locally without server round-trips. This milestone reframes the AI competition: cloud APIs now compete against zero-latency, zero-cost on-device inference for everyday tasks. Developers building with cloud APIs need to clearly justify the added value.",
    source: "Apple earnings call and developer announcements, Q1 2026",
    relatedCategory: "productivity",
  },
  {
    id: "signal-2026-04-05",
    date: "2026-04-05",
    title: "OpenAI's o3 Scores 87.5% on ARC-AGI — Near Human Level",
    shortTeaser: "The once-unbreakable benchmark for general fluid intelligence has nearly fallen to a single AI system, marking a philosophical milestone.",
    fullText: "ARC-AGI was designed by François Chollet specifically to resist pattern memorization and test genuine abstract reasoning. OpenAI's o3 achieved 87.5% — compared to a human average of ~85%. This result has divided the AI research community: some argue it definitively crosses into AGI territory, while others point out o3's massive compute cost per task (~$1000/sample) makes it impractical. Either way, the benchmark that was supposed to be AI-proof has effectively fallen.",
    source: "ARC Prize Foundation results, early 2026",
    relatedCategory: "research",
  },
  {
    id: "signal-2026-04-04",
    date: "2026-04-04",
    title: "Microsoft Deploys Autonomous AI Agents Across 365 Suite",
    shortTeaser: "Copilot agents now handle multi-step work tasks end-to-end in Word, Excel, Outlook, and Teams — without user prompting.",
    fullText: "Microsoft's Copilot Wave 3 introduces 'Autonomous Agents' that can observe your work patterns and proactively draft emails, update spreadsheets, and schedule meetings based on context — not just commands. Early enterprise pilots show 40% reduction in routine admin time. The shift from reactive assistant to proactive agent represents a fundamental change in how knowledge workers interact with software tools daily.",
    source: "Microsoft Build 2026 keynote and enterprise pilot data",
    relatedCategory: "automation",
  },
  {
    id: "signal-2026-04-03",
    date: "2026-04-03",
    title: "Meta Releases Llama 4 with 10M Token Context Window",
    shortTeaser: "An open-weight model with a context window large enough to fit entire codebases, legal documents, or book manuscripts changes what's possible locally.",
    fullText: "Meta's Llama 4 Scout variant supports a 10-million token context window — enough to fit roughly 7,500 pages of text. Released under a permissive license, it lets any developer run ultra-long-context analysis locally. Early use cases include full codebase auditing, entire legal case ingestion, and deep financial report analysis. The model runs efficiently on a single 8xH100 node, putting it within reach of mid-sized engineering teams.",
    source: "Meta AI blog and Llama 4 model card, March 2026",
    relatedCategory: "rag",
  },
  {
    id: "signal-2026-04-02",
    date: "2026-04-02",
    title: "The 'Reasoning Tax': Why Thinking Models Cost 10× More",
    shortTeaser: "Extended reasoning modes in o3, Claude 4, and Gemini 2 unlock new capabilities but create a hidden cost trap for teams not watching token usage.",
    fullText: "Benchmark-beating 'reasoning' or 'thinking' modes in frontier models achieve results by generating thousands of intermediate tokens before producing an answer. While this dramatically improves accuracy on hard problems, it also increases inference costs by 5-15× versus standard modes. Engineering teams are discovering that enabling reasoning by default on all queries quickly blows API budgets. The emerging best practice: route only genuinely hard tasks to reasoning mode, use fast models for everything else.",
    source: "Multiple engineering post-mortems and API provider pricing analysis, 2026",
    relatedCategory: "prompting",
  },
  {
    id: "signal-2026-04-01",
    date: "2026-04-01",
    title: "AI Writes 25% of Code at Google, Says CEO Sundar Pichai",
    shortTeaser: "A quarter of new code at the world's largest software company is now AI-generated — and the percentage is accelerating.",
    fullText: "Sundar Pichai revealed in an earnings call that approximately 25% of new code at Google is now produced by AI systems, up from 'a small percentage' just 18 months ago. He noted that human engineers review all AI-generated code, but the velocity boost is substantial. This figure is consistent with similar disclosures from Meta and Microsoft. For software engineers, this signals that AI-assisted development is no longer optional — it's a competitive baseline.",
    source: "Google Q1 2026 earnings call, Sundar Pichai",
    relatedCategory: "python",
  },
  {
    id: "signal-2026-03-31",
    date: "2026-03-31",
    title: "Perplexity Launches 'Deep Research' for Enterprise",
    shortTeaser: "Multi-step AI research agents that autonomously browse, synthesize, and cite sources are now available at scale for knowledge workers.",
    fullText: "Perplexity's Deep Research mode chains together dozens of search queries, reads full web pages, and synthesizes cited reports in minutes — tasks that would take a human researcher hours or days. The enterprise tier adds SOC 2 compliance, custom knowledge bases, and team sharing. Early adopters in consulting, law, and finance report 60-80% reduction in background research time. The quality ceiling is now 'good enough for first drafts' on most professional research tasks.",
    source: "Perplexity product announcements and enterprise case studies, Q1 2026",
    relatedCategory: "research",
  },
  {
    id: "signal-2026-03-30",
    date: "2026-03-30",
    title: "Notion AI Reaches 10M Active Daily Users",
    shortTeaser: "Embedded AI in productivity tools has quietly become the dominant way most knowledge workers interact with AI — not dedicated chat apps.",
    fullText: "Notion reported 10 million daily active users of its AI features — more than many standalone AI products. This reflects a broader trend: people prefer AI woven into the tools they already use rather than switching contexts to a separate app. For builders and PMs, this is a strategic signal — the distribution moat of existing software platforms is proving decisive in AI adoption. Building a standalone AI tool now means competing against every SaaS product that has added AI.",
    source: "Notion company blog and press releases, March 2026",
    relatedCategory: "productivity",
  },
  {
    id: "signal-2026-03-29",
    date: "2026-03-29",
    title: "Anthropic's Model Spec Leaks — AI Given Explicit Values Hierarchy",
    shortTeaser: "The internal document guiding Claude's behavior reveals a priority stack: broadly safe > broadly ethical > adherent to principles > helpful.",
    fullText: "A leaked version of Anthropic's internal 'Model Spec' — the document that shapes Claude's values and behavior — was posted and rapidly circulated online. It reveals a nuanced priority hierarchy and extensive reasoning about edge cases, operator vs user conflicts, and 'big-picture safety.' The document is notable for its philosophical depth and its explicit acknowledgment that Claude may have functional emotions. It became one of the most-discussed documents in AI safety and alignment circles this year.",
    source: "Leaked Anthropic Model Spec, March 2026 + community analysis",
    relatedCategory: "research",
  },
  {
    id: "signal-2026-03-28",
    date: "2026-03-28",
    title: "Gemini 2.0 Flash Becomes Default API for 2M Developers",
    shortTeaser: "Google's fastest model is now the go-to for latency-sensitive applications, reshaping the developer tool landscape.",
    fullText: "Gemini 2.0 Flash achieved what GPT-4o did in 2024 — becoming the default workhorse for developers who need speed over maximum capability. With sub-200ms TTFT (time to first token) and strong multimodal performance, it's displaced alternatives in real-time voice, live video analysis, and interactive agent workflows. Google's aggressive free tier has accelerated adoption, with over 2 million developers now using it as their primary model.",
    source: "Google I/O 2026 developer statistics",
    relatedCategory: "automation",
  },
  {
    id: "signal-2026-03-27",
    date: "2026-03-27",
    title: "OpenAI Launches Operator: AI That Books, Buys, and Acts for You",
    shortTeaser: "Autonomous web agents that take real actions on your behalf — purchases, bookings, form submissions — are now in public rollout.",
    fullText: "OpenAI's Operator product crossed 1 million active users in its first month after public release. Unlike chat interfaces, Operator operates a real browser, navigates websites, and takes actions with real-world consequences. Use cases range from booking restaurant reservations to filing expense reports to purchasing event tickets. The product raises major questions about liability, fraud, and trust — and has already prompted response from browser vendors and major e-commerce platforms.",
    source: "OpenAI product blog and launch metrics, March 2026",
    relatedCategory: "automation",
  },
  {
    id: "signal-2026-03-26",
    date: "2026-03-26",
    title: "The '$500 PhD Intern': AI Research Assistance Reaches Professional Grade",
    shortTeaser: "Research tasks that once required a graduate student can now be delegated to AI for pennies — disrupting how academic and corporate R&D works.",
    fullText: "A widely-shared analysis demonstrated that a combination of Perplexity Deep Research, Claude 4 Opus, and Python scripting could replicate a junior academic researcher's month of work in under 2 hours for approximately $8 in API costs. Tasks included literature review, data extraction, summarization, and hypothesis generation. While quality oversight is still essential, the economic disruption to research-heavy industries — pharma, finance, consulting — is now measurable and accelerating.",
    source: "Independent analysis published on Substack and HN, March 2026",
    relatedCategory: "research",
  },
  {
    id: "signal-2026-03-25",
    date: "2026-03-25",
    title: "Voice AI Passes the Turing Test in Blind Trials",
    shortTeaser: "In independent tests, GPT-4o voice and Hume AI's EVI 2 were indistinguishable from human speakers by a majority of listeners.",
    fullText: "A peer-reviewed study published in Nature Human Behaviour found that listeners could not reliably distinguish between AI voice agents and human speakers in 60-second conversations. Both GPT-4o voice and Hume AI's EVI 2 — which models emotional expression — passed at statistically significant rates. The study has immediate implications for customer service, fraud detection, and identity verification systems that rely on voice as a trust signal.",
    source: "Nature Human Behaviour, March 2026 + Hume AI research",
    relatedCategory: "prompting",
  },
  {
    id: "signal-2026-03-24",
    date: "2026-03-24",
    title: "China's DeepSeek R2 Matches o3 at 1/10th the Cost",
    shortTeaser: "The second major efficiency shock from a Chinese lab forces a global rethink of compute moats and API pricing strategy.",
    fullText: "DeepSeek R2's release recreated the shock of R1 — delivering o3-comparable reasoning performance at a fraction of the training cost. The open-weight release triggered another market selloff in Nvidia and cloud stocks. More importantly, it validated that architectural efficiency innovation can compress what appeared to be insurmountable compute advantages. Western labs are now accelerating their own efficiency research as a strategic priority, not just an engineering goal.",
    source: "DeepSeek technical report and market analysis, March 2026",
    relatedCategory: "research",
  },
  {
    id: "signal-2026-03-23",
    date: "2026-03-23",
    title: "AI-Assisted Writing Now Default in 80% of Fortune 500",
    shortTeaser: "Corporate adoption of AI writing tools has crossed a tipping point — the question is no longer whether to use AI to write, but how to use it well.",
    fullText: "A McKinsey survey of Fortune 500 communications and marketing teams found that 81% now use AI writing assistance as a standard part of their workflow. However, only 23% report high satisfaction with output quality, citing tone inconsistency and factual errors as top concerns. The report identifies prompt engineering and human editorial oversight as the two highest-leverage skills for teams wanting to extract real productivity gains rather than just speed.",
    source: "McKinsey Digital survey, Q1 2026",
    relatedCategory: "writing",
  },
  {
    id: "signal-2026-03-22",
    date: "2026-03-22",
    title: "Runway Gen-4 Produces Broadcast-Quality Video from Text",
    shortTeaser: "AI video generation has crossed the threshold where outputs are indistinguishable from professional studio production for short-form content.",
    fullText: "Runway's Gen-4 model, released in March 2026, produces 4K video clips with consistent characters, physics-accurate motion, and cinematic lighting — from text prompts alone. Independent film editors blind-tested clips and rated 34% as 'indistinguishable from real footage.' Hollywood studios have begun integrating it for B-roll and pre-visualization, while independent creators are producing full short films. The cost per minute of broadcast-quality video has dropped from ~$10,000 to under $2.",
    source: "Runway Gen-4 launch and independent filmmaker reports, March 2026",
    relatedCategory: "automation",
  },
  {
    id: "signal-2026-03-21",
    date: "2026-03-21",
    title: "The Prompt Engineer Role Is Dead — Long Live the AI Architect",
    shortTeaser: "As models become instruction-following by default, the skill premium shifts from writing prompts to designing systems, workflows, and evals.",
    fullText: "Multiple large tech companies have officially retired the 'Prompt Engineer' job title, folding the function into broader 'AI Product Engineer' or 'AI Systems Architect' roles. The shift reflects model capability improvements — basic prompting is now trivially easy for anyone. The scarce skill is now system design: knowing when to use which model, how to build reliable eval pipelines, how to architect agentic workflows, and how to manage cost vs quality tradeoffs at scale.",
    source: "LinkedIn hiring data analysis and multiple company announcements, Q1 2026",
    relatedCategory: "prompting",
  },
  {
    id: "signal-2026-03-20",
    date: "2026-03-20",
    title: "RAG Is Becoming Obsolete for Most Enterprise Use Cases",
    shortTeaser: "10M-token context windows are eliminating the need for retrieval pipelines — entire knowledge bases now fit in a single prompt.",
    fullText: "With Llama 4 Scout's 10M context window and Google's 2M-token Gemini models, the original rationale for RAG (retrieval-augmented generation) — models can't hold enough context — is collapsing for many use cases. Teams are discovering that shoving entire policy manuals, codebases, or support histories directly into context produces better answers with less infrastructure. RAG still wins for truly massive knowledge bases and real-time data, but 'naive RAG' for medium-sized corpora is increasingly obsolete.",
    source: "Multiple engineering blog posts and benchmarks, Q1 2026",
    relatedCategory: "rag",
  },
  {
    id: "signal-2026-03-19",
    date: "2026-03-19",
    title: "Jensen Huang: 'Every Company Will Have an AI Factory'",
    shortTeaser: "Nvidia's CEO reframes enterprise AI from 'software feature' to 'core infrastructure' — predicting on-premise AI compute for every major organization.",
    fullText: "At GTC 2026, Jensen Huang argued that within five years, AI inference infrastructure will be as standard as corporate data centers were in the 1990s. He unveiled Nvidia's 'AI Factory' reference architecture for enterprises — complete GPU clusters designed to run continuously, generating intelligence as output the way factories generate goods. The concept is already materializing: JPMorgan, Goldman, and several pharmaceutical firms have announced private AI infrastructure build-outs exceeding $500M each.",
    source: "Nvidia GTC 2026 keynote, Jensen Huang",
    relatedCategory: "data",
  },
  {
    id: "signal-2026-03-18",
    date: "2026-03-18",
    title: "AI Beats Doctors at Diagnosing Rare Diseases in New Study",
    shortTeaser: "GPT-4o with medical tools correctly identified rare conditions in 85% of cases versus 54% for specialist physicians in a landmark trial.",
    fullText: "A Stanford Medical School study published in NEJM compared GPT-4o with access to medical databases against specialist physicians on a set of 300 rare disease cases. The AI achieved 85% correct diagnosis versus 54% for human specialists. Importantly, the AI's advantage was largest on the rarest conditions — exactly where human expertise is scarcest. The study has re-energized debates about AI as a diagnostic tool and accelerated several health system pilots in the EU and US.",
    source: "Stanford + NEJM study, March 2026",
    relatedCategory: "research",
  },
  {
    id: "signal-2026-03-17",
    date: "2026-03-17",
    title: "The First AI-Discovered Drug Enters Phase 2 Clinical Trials",
    shortTeaser: "A molecule fully designed by AI with zero human hypothesis input is now being tested in humans — a landmark moment for scientific AI.",
    fullText: "Isomorphic Labs (DeepMind spinout) announced its first fully AI-discovered drug candidate has entered Phase 2 clinical trials for a rare form of liver cancer. The molecule was identified, optimized, and prioritized entirely by AI systems with no human-generated initial hypothesis. The traditional drug discovery timeline for reaching Phase 2 is 5-8 years; this candidate took 18 months from target identification to trial enrollment. If successful, it would fundamentally validate AI-first pharmaceutical research.",
    source: "Isomorphic Labs press release and DeepMind research blog, March 2026",
    relatedCategory: "research",
  },
  {
    id: "signal-2026-03-16",
    date: "2026-03-16",
    title: "Cursor Surpasses 1M Paying Developers — AI Coding Is the Norm",
    shortTeaser: "The AI code editor has crossed the million-subscriber threshold, confirming that AI-assisted development is now the professional standard, not a novelty.",
    fullText: "Cursor announced 1 million paying subscribers, generating over $100M ARR just 18 months after its public launch. The product's ability to understand entire codebases and make multi-file edits has made it the default IDE for a generation of developers. GitHub Copilot, Codeium, and JetBrains AI are all competing aggressively, but the winner of this category stands to influence how hundreds of millions of lines of code are written daily. Coding without AI assistance is increasingly seen as a competitive disadvantage.",
    source: "Cursor company blog and TechCrunch reporting, March 2026",
    relatedCategory: "python",
  },
];

export function getSignalByDate(dateStr) {
  return SIGNALS.find(s => s.date === dateStr) ?? null;
}

export function getTodaySignal() {
  const today = new Date().toISOString().split("T")[0];
  // Return today's signal if exists, otherwise the most recent one
  return SIGNALS.find(s => s.date === today) ?? SIGNALS[0];
}

export function getSignalsGroupedByMonth() {
  const groups = {};
  SIGNALS.forEach(signal => {
    const [year, month] = signal.date.split("-");
    const key = `${year}-${month}`;
    if (!groups[key]) groups[key] = [];
    groups[key].push(signal);
  });
  // Sort each group by date descending
  Object.keys(groups).forEach(k => groups[k].sort((a, b) => b.date.localeCompare(a.date)));
  return groups;
}